"use client"

import { ThemeProvider } from 'styled-components'
import { LightTheme } from '@/Themes/Light'
import { DarkTheme } from '@/Themes/Dark'
import { GlobalStyle } from '@/Themes/Global'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DashBoard App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={DarkTheme}>
        <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
        <GlobalStyle />
      </ThemeProvider>
    </html>
  )
}
 